import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Livewire/**/*.php',
    ],

    theme: {
        extend: {
            colors: {
                fleet: {
                    page: '#f0f4fa',
                    sidebar: '#e8eef5',
                    card: '#ffffff',
                    ink: '#1E293B',
                    secondary: '#64748B',
                    muted: '#94a3b8',
                    border: '#cbd5e1',
                    primary: '#002B5C',
                    tertiary: '#F97316',
                    success: '#10b981',
                    profit: '#166534',
                    danger: '#dc2626',
                    dark: '#002B5C',
                },
                /** Auth / marketing screens (split layout) */
                background: '#f7f9fb',
                'on-background': '#2d3337',
                'on-error': '#fff7f7',
                tertiary: '#005bc4',
                'surface-bright': '#f7f9fb',
                'on-tertiary-fixed': '#001f4b',
                'on-primary-fixed-variant': '#5800c2',
                'primary-fixed-dim': '#c2a4ff',
                'outline-variant': '#acb3b7',
                'surface-variant': '#dde3e7',
                'surface-container-low': '#f1f4f6',
                'surface-tint': '#742fe5',
                'on-surface-variant': '#596063',
                'on-surface': '#2d3337',
                'inverse-on-surface': '#9a9d9f',
                'primary-container': '#ceb5ff',
                'on-primary': '#fdf7ff',
                'on-tertiary': '#f9f8ff',
                'surface-container': '#eaeef1',
                'tertiary-fixed-dim': '#81aaff',
                'on-secondary-container': '#005e3f',
                'surface-container-high': '#e3e9ec',
                'inverse-surface': '#0b0f10',
                'tertiary-fixed': '#98b8ff',
                primary: '#742fe5',
                'on-primary-container': '#4d00ac',
                'on-secondary-fixed-variant': '#006947',
                'surface-container-lowest': '#ffffff',
                'on-secondary': '#e6ffee',
                'tertiary-container': '#98b8ff',
                secondary: '#006d4a',
                'inverse-primary': '#a476ff',
                surface: '#f7f9fb',
                'on-secondary-fixed': '#004930',
                'on-error-container': '#68001f',
                outline: '#757c7f',
                'surface-container-highest': '#dde3e7',
                'secondary-fixed-dim': '#5fedb0',
                'secondary-dim': '#005f40',
                'on-tertiary-fixed-variant': '#003c87',
                'tertiary-dim': '#004fad',
                'on-tertiary-container': '#003476',
                'error-dim': '#770326',
                'primary-dim': '#681ad9',
                'on-primary-fixed': '#340078',
                error: '#ac3149',
                'secondary-fixed': '#6ffbbe',
                'primary-fixed': '#ceb5ff',
                'error-container': '#f76a80',
                'secondary-container': '#6ffbbe',
                'surface-dim': '#d3dbdf',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['"Plus Jakarta Sans"', 'Inter', ...defaultTheme.fontFamily.sans],
                body: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'fleet-display': ['1.5rem', { lineHeight: '2rem', fontWeight: '700', letterSpacing: '-0.02em' }],
                'fleet-modal': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '700' }],
                'fleet-body': ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
                'fleet-label': ['0.6875rem', { lineHeight: '1rem', fontWeight: '600', letterSpacing: '0.06em' }],
            },
            boxShadow: {
                fleet: '0 1px 3px 0 rgb(0 43 92 / 0.06), 0 1px 2px -1px rgb(0 43 92 / 0.06)',
                'fleet-card': '0 4px 24px -4px rgb(0 43 92 / 0.08)',
            },
        },
    },

    plugins: [forms],
};
