import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Livewire/**/*.php',
    ],

    theme: {
        extend: {
            colors: {
                fleet: {
                    page: '#f8fafc',
                    sidebar: '#f3f4f6',
                    card: '#ffffff',
                    ink: '#0f172a',
                    secondary: '#475569',
                    muted: '#64748b',
                    border: '#e2e8f0',
                    primary: '#2563eb',
                    success: '#10b981',
                    profit: '#1e5128',
                    danger: '#dc2626',
                    dark: '#111827',
                },
                /** Auth / marketing screens (split layout) */
                background: '#f7f9fb',
                'on-background': '#2d3337',
                'on-error': '#fff7f7',
                tertiary: '#005bc4',
                'surface-bright': '#f7f9fb',
                'on-tertiary-fixed': '#001f4b',
                'on-primary-fixed-variant': '#5800c2',
                'primary-fixed-dim': '#c2a4ff',
                'outline-variant': '#acb3b7',
                'surface-variant': '#dde3e7',
                'surface-container-low': '#f1f4f6',
                'surface-tint': '#742fe5',
                'on-surface-variant': '#596063',
                'on-surface': '#2d3337',
                'inverse-on-surface': '#9a9d9f',
                'primary-container': '#ceb5ff',
                'on-primary': '#fdf7ff',
                'on-tertiary': '#f9f8ff',
                'surface-container': '#eaeef1',
                'tertiary-fixed-dim': '#81aaff',
                'on-secondary-container': '#005e3f',
                'surface-container-high': '#e3e9ec',
                'inverse-surface': '#0b0f10',
                'tertiary-fixed': '#98b8ff',
                primary: '#742fe5',
                'on-primary-container': '#4d00ac',
                'on-secondary-fixed-variant': '#006947',
                'surface-container-lowest': '#ffffff',
                'on-secondary': '#e6ffee',
                'tertiary-container': '#98b8ff',
                secondary: '#006d4a',
                'inverse-primary': '#a476ff',
                surface: '#f7f9fb',
                'on-secondary-fixed': '#004930',
                'on-error-container': '#68001f',
                outline: '#757c7f',
                'surface-container-highest': '#dde3e7',
                'secondary-fixed-dim': '#5fedb0',
                'secondary-dim': '#005f40',
                'on-tertiary-fixed-variant': '#003c87',
                'tertiary-dim': '#004fad',
                'on-tertiary-container': '#003476',
                'error-dim': '#770326',
                'primary-dim': '#681ad9',
                'on-primary-fixed': '#340078',
                error: '#ac3149',
                'secondary-fixed': '#6ffbbe',
                'primary-fixed': '#ceb5ff',
                'error-container': '#f76a80',
                'secondary-container': '#6ffbbe',
                'surface-dim': '#d3dbdf',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['"Plus Jakarta Sans"', 'Inter', ...defaultTheme.fontFamily.sans],
                body: ['Inter', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
